server:
  port: 8080
  error:
    include-message: always
  
spring:
  config:
    import: sm://    
  cloud:
    gcp:
      config:
        enabled: true
        project-id: gcp-demo-412804
      credentials:
        location: classpath:gcp-service-account/gcp-demo-service-account-1.json           
      logging:
        enabled: true        
      project-id: gcp-demo-412804
      trace:
        enabled: true
        project-id: gcp-demo-412804
        credentials:
          location: classpath:gcp-service-account/gcp-demo-service-account-1.json
      secretmanager:
        enabled: true
        project-id: gcp-demo-412804
        credentials:
          location: classpath:gcp-service-account/gcp-demo-service-account-1.json
         
#  r2dbc:
#    url: r2dbc:postgresql://localhost:5432/MyDatabase
#    username: postgres
#    password: admin
#  data:
#    r2dbc:
#      repositories:
#        enabled: true
          
logging:
  config: classpath:logback-spring.xml
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG   
 

dbname: ${sm://projects/443415746459/secrets/databaseUrl1}
dbusername: ${sm://projects/443415746459/secrets/databaseName1}
dbpwd: ${sm://projects/443415746459/secrets/databasepwd2}
